# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1232eaccef54dcfdbdc7fe9097425171d64131f5d0814fed4980b40d0cda5602f5c6d716d441d41bebf87afac9061bd9fc48bea7719c92890a03a9c8a0e2818

test:
  secret_key_base: 122fbc075b14b32cb05269ff01f8d439bd6cbc01847db2ab5f0b02ffb8fdc3727f3132d97f5f8285850d027949fe6850f61d048984ef4c9da5c73631d035153a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
